# Generated by Django 4.2.11 on 2025-01-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'normal user'), (2, 'ambassador'), (3, 'admin')], null=True),
        ),
    ]
