# Generated by Django 4.2.11 on 2025-01-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(default=dict, help_text='User preferences for notifications.', null=True),
        ),
    ]
