# Generated by Django 4.2.11 on 2025-01-21 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_notification_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_preferences',
        ),
    ]
