# Generated by Django 4.2.11 on 2025-03-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alerts_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='alerts_upvoted',
            field=models.PositiveIntegerField(default=0, help_text='Number of alerts upvoted by other users.'),
        ),
    ]
