# Generated by Django 4.2.11 on 2025-03-02 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text='Identifier for the device', max_length=100)),
                ('token', models.CharField(editable=False, help_text='Access token', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time of the token')),
                ('expires_at', models.DateTimeField(help_text='Expiration time of the token')),
                ('is_revoked', models.BooleanField(default=False, help_text='Revocation status')),
                ('user', models.ForeignKey(help_text='User associated with the token', on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
