# Generated by Django 4.2.11 on 2024-12-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='hazard_type',
            field=models.CharField(choices=[('earthquake', 'Earthquake'), ('flood', 'Heavy Flood'), ('tornado', 'Tornado'), ('fire', 'Fire'), ('storm', 'Storm'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='reported_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
