# Generated by Django 4.2.11 on 2025-01-24 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_updated_at_alter_alert_hazard_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-delete flag. If False, the alert is considered deleted.'),
        ),
        migrations.AlterField(
            model_name='tornado',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, help_text='Wind speed in km/h.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
