# Generated by Django 4.2.11 on 2025-01-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_is_active_alter_tornado_wind_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='effect_radius',
            field=models.PositiveIntegerField(blank=True, help_text='Radius of effect in meters (optional)', null=True),
        ),
    ]
