# Generated by Django 4.2.11 on 2025-02-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_effect_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='effect_radius',
            field=models.PositiveIntegerField(help_text='Radius of effect in meters'),
        ),
    ]
