# Generated by Django 4.2.11 on 2025-02-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_alert_effect_radius'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='deletion_time',
            new_name='soft_deletion_time',
        ),
    ]
