# Generated by Django 4.2.11 on 2025-02-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_rename_deletion_time_alert_soft_deletion_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Storm',
        ),
        migrations.RemoveField(
            model_name='fire',
            name='affected_area',
        ),
        migrations.RemoveField(
            model_name='flood',
            name='affected_area',
        ),
        migrations.RemoveField(
            model_name='tornado',
            name='wind_speed',
        ),
        migrations.AddField(
            model_name='fire',
            name='fire_intensity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], help_text='Intensity of the fire.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flood',
            name='severity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('major', 'Major')], help_text='Severity of the flood.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tornado',
            name='category',
            field=models.CharField(blank=True, choices=[('F0', 'F0'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5')], help_text='Category of the tornado.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Depth of the earthquake in kilometers.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='magnitude',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Magnitude of the earthquake.', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='flood',
            name='water_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Water level in meters.', max_digits=5, null=True),
        ),
    ]
