# Generated by Django 4.2.11 on 2025-03-01 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_delete_storm_remove_fire_affected_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='hazard_type',
        ),
    ]
