# Generated by Django 4.2.11 on 2025-03-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_remove_alert_hazard_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tornado',
            name='category',
            field=models.CharField(blank=True, choices=[('EF0', 'EF0'), ('EF1', 'EF1'), ('EF2', 'EF2'), ('EF3', 'EF3'), ('EF4', 'EF4'), ('EF5', 'EF5')], help_text='Category of the tornado.', max_length=3, null=True),
        ),
    ]
