# Generated by Django 4.2.11 on 2025-03-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alter_tornado_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of the alert.', null=True),
        ),
    ]
