# Generated by Django 4.2.11 on 2025-03-05 02:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0010_alter_alert_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='effect_radius',
            field=models.PositiveIntegerField(help_text='Radius of effect in meters - max: 100 km.', validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.CreateModel(
            name='AlertUserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(help_text='True: Upvote, False: Downvote.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'alert')},
            },
        ),
    ]
